### ISSUE TITLE
averaged rank

### ISSUE THREAD

**Issue by cxw-droid** [SamsungSAILMontreal/ForestDiffusion#10]
Hi, thank you for your awesome paper!

May I know how to calculate the averaged rank for all the methods (the rank of each method relative to other methods)? I did not find the details in the paper or in the `script_generation.py` code. I also compared table 2 and table 8, but did not figured it out. Thanks.

**Comment by AlexiaJM** [comment]
Hi,

You can see it in the messy R code here: https://github.com/SamsungSAILMontreal/ForestDiffusion/blob/992b13816da004cf2411f666ac95599a7d60907b/Results/generation_script.R#L137.

I just applied the rank function in R (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/rank) across the different methods separately for each metric.
