### ISSUE TITLE
Density estimation

### ISSUE THREAD

**Issue by calvinmccarter** [SamsungSAILMontreal/ForestDiffusion#7]
This method worked really well on my data! Is it possible to perform density estimation with ForestDiffusion?

**Comment by AlexiaJM** [comment]
Hi Calvin,

Our method does not perform density estimation. It could be possible to implement it following the approach used in the zero-shot classification, but it would be computationally intensive (n_t=10, n_z=10, 250 values = 250*10*10 xgboost predictions) and I'm not sure what would be the advantage over using standard kernel-based density estimation.

Alexia

**Comment by calvinmccarter** [comment]
Hi Alexia, thanks -- makes sense!
